# VERİ HAZIRLAMA

In [1]:
import pandas as pd
import numpy as np

In [2]:
veriler = pd.read_csv('train.csv', parse_dates=['Tarih'])

In [3]:
veriler.isna().sum()
veriler.describe()
veriler.info()
veriler.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 40152 entries, 0 to 40151
Data columns (total 2 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Tarih                   40152 non-null  datetime64[ns]
 1   Dağıtılan Enerji (MWh)  40152 non-null  float64
dtypes: datetime64[ns](1), float64(1)
memory usage: 627.5 KB

                Tarih  Dağıtılan Enerji (MWh)
0 2018-01-01 00:00:00             1593.944216
1 2018-01-01 01:00:00             1513.933887
2 2018-01-01 02:00:00             1402.612637
3 2018-01-01 03:00:00             1278.527266
4 2018-01-01 04:00:00             1220.697701

In [4]:
veriler = veriler.rename(columns={"Dağıtılan Enerji (MWh)" : "DE"})

In [5]:
veriler.head()

                Tarih           DE
0 2018-01-01 00:00:00  1593.944216
1 2018-01-01 01:00:00  1513.933887
2 2018-01-01 02:00:00  1402.612637
3 2018-01-01 03:00:00  1278.527266
4 2018-01-01 04:00:00  1220.697701

In [6]:
veriler['Gün'] = veriler['Tarih'].dt.dayofweek
veriler["GünSırası"]=veriler["Tarih"].dt.day
veriler['Ay'] = veriler['Tarih'].dt.month
veriler['Yıl'] = veriler['Tarih'].dt.year
veriler['Saat'] = veriler['Tarih'].dt.hour
veriler['Mevsim'] = (veriler['Tarih'].dt.month % 12 + 3) // 3
veriler['Hafta Sonu'] = veriler['Gün'].apply(lambda x: 1 if x in [5, 6] else 0)
veriler['Gece'] = veriler['Saat'].apply(lambda x: 1 if x in [18,19,20,21,22,23,0,1,2,3,4,5] else 0)

In [7]:
def add_quality(Saat):
    if 0<=Saat and Saat <=4: 
        return 0
    elif Saat>20:
        return 0
    elif 11<Saat and Saat<=12:
        return 0
    elif 6<Saat and Saat<=11:
        return 1
    elif 12<Saat and Saat<=14:
        return 1
    elif 5<=Saat and Saat<=6:
        return 2
    elif 14<Saat and Saat<=20:
        return 2
    
veriler["Artmış Mı"] = veriler["Saat"].apply(add_quality)

In [8]:
veriler.head(24000)
#veriler.info()

,Tarih,DE,Gün,GünSırası,Ay,Yıl,Saat,Mevsim,Hafta Sonu,Gece,Artmış Mı
0,2018-01-01 00:00:00,1593.944216,0,1,1,2018,0,1,0,1,0
1,2018-01-01 01:00:00,1513.933887,0,1,1,2018,1,1,0,1,0
2,2018-01-01 02:00:00,1402.612637,0,1,1,2018,2,1,0,1,0
3,2018-01-01 03:00:00,1278.527266,0,1,1,2018,3,1,0,1,0
4,2018-01-01 04:00:00,1220.697701,0,1,1,2018,4,1,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...
23995,2020-09-26 19:00:00,2125.575504,5,26,9,2020,19,4,1,1,2
23996,2020-09-26 20:00:00,2070.230938,5,26,9,2020,20,4,1,1,2
23997,2020-09-26 21:00:00,1960.334625,5,26,9,2020,21,4,1,1,0
23998,2020-09-26 22:00:00,1862.313947,5,26,9,2020,22,4,1,1,0
23999,2020-09-26 23:00:00,1746.882155,5,26,9,2020,23,4,1,1,0

In [9]:
veriler = veriler.drop('Tarih', axis=1)
veriler= veriler.astype(float)
veri_yedek= veriler
veriler.head(24000)
#veriler.info()

,DE,Gün,GünSırası,Ay,Yıl,Saat,Mevsim,Hafta Sonu,Gece,Artmış Mı
0,1593.944216,0.0,1.0,1.0,2018.0,0.0,1.0,0.0,1.0,0.0
1,1513.933887,0.0,1.0,1.0,2018.0,1.0,1.0,0.0,1.0,0.0
2,1402.612637,0.0,1.0,1.0,2018.0,2.0,1.0,0.0,1.0,0.0
3,1278.527266,0.0,1.0,1.0,2018.0,3.0,1.0,0.0,1.0,0.0
4,1220.697701,0.0,1.0,1.0,2018.0,4.0,1.0,0.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...
23995,2125.575504,5.0,26.0,9.0,2020.0,19.0,4.0,1.0,1.0,2.0
23996,2070.230938,5.0,26.0,9.0,2020.0,20.0,4.0,1.0,1.0,2.0
23997,1960.334625,5.0,26.0,9.0,2020.0,21.0,4.0,1.0,1.0,0.0
23998,1862.313947,5.0,26.0,9.0,2020.0,22.0,4.0,1.0,1.0,0.0
23999,1746.882155,5.0,26.0,9.0,2020.0,23.0,4.0,1.0,1.0,0.0

# MODEL EĞİTME

In [10]:
from sklearn.model_selection import train_test_split
def mape(y_test, y_pred):
    return np.mean(np.abs((y_test - y_pred) / y_test)) * 100

In [11]:
X= veriler.drop(['DE'], axis=1)
X_train=[]
X_test=[]
for i in range(len(X)):
    if X.iloc[i]['Ay']== 7 and X.iloc[i]['Yıl']==2022:
       X_test.append(X.iloc[i])
    else:
        X_train.append(X.iloc[i])

In [12]:
X_train = pd.DataFrame(X_train, columns=['Gün', 'GünSırası', 'Ay','Yıl', 'Saat', 'Mevsim','Hafta Sonu', 'Gece', 'Artmış Mı'])
X_test= pd.DataFrame(X_test, columns=['Gün', 'GünSırası', 'Ay','Yıl', 'Saat', 'Mevsim','Hafta Sonu', 'Gece', 'Artmış Mı'])

In [13]:
X_train

       Gün  GünSırası   Ay     Yıl  Saat  Mevsim  Hafta Sonu  Gece  Artmış Mı
0      0.0        1.0  1.0  2018.0   0.0     1.0         0.0   1.0        0.0
1      0.0        1.0  1.0  2018.0   1.0     1.0         0.0   1.0        0.0
2      0.0        1.0  1.0  2018.0   2.0     1.0         0.0   1.0        0.0
3      0.0        1.0  1.0  2018.0   3.0     1.0         0.0   1.0        0.0
4      0.0        1.0  1.0  2018.0   4.0     1.0         0.0   1.0        0.0
...    ...        ...  ...     ...   ...     ...         ...   ...        ...
39403  3.0       30.0  6.0  2022.0  19.0     3.0         0.0   1.0        2.0
39404  3.0       30.0  6.0  2022.0  20.0     3.0         0.0   1.0        2.0
39405  3.0       30.0  6.0  2022.0  21.0     3.0         0.0   1.0        0.0
39406  3.0       30.0  6.0  2022.0  22.0     3.0         0.0   1.0        0.0
39407  3.0       30.0  6.0  2022.0  23.0     3.0         0.0   1.0        0.0

[39408 rows x 9 columns]

In [14]:
X_test

       Gün  GünSırası   Ay     Yıl  Saat  Mevsim  Hafta Sonu  Gece  Artmış Mı
39408  4.0        1.0  7.0  2022.0   0.0     3.0         0.0   1.0        0.0
39409  4.0        1.0  7.0  2022.0   1.0     3.0         0.0   1.0        0.0
39410  4.0        1.0  7.0  2022.0   2.0     3.0         0.0   1.0        0.0
39411  4.0        1.0  7.0  2022.0   3.0     3.0         0.0   1.0        0.0
39412  4.0        1.0  7.0  2022.0   4.0     3.0         0.0   1.0        0.0
...    ...        ...  ...     ...   ...     ...         ...   ...        ...
40147  6.0       31.0  7.0  2022.0  19.0     3.0         1.0   1.0        2.0
40148  6.0       31.0  7.0  2022.0  20.0     3.0         1.0   1.0        2.0
40149  6.0       31.0  7.0  2022.0  21.0     3.0         1.0   1.0        0.0
40150  6.0       31.0  7.0  2022.0  22.0     3.0         1.0   1.0        0.0
40151  6.0       31.0  7.0  2022.0  23.0     3.0         1.0   1.0        0.0

[744 rows x 9 columns]

In [15]:
Y_train=[]
Y_test=[]
for i in range(len(veriler)):
    if veriler.iloc[i]['Ay']== 7 and veriler.iloc[i]['Yıl']==2022:
       Y_test.append(veriler.iloc[i]['DE'])
    else:
        Y_train.append(veriler.iloc[i]['DE'])

In [16]:
Y_train = pd.Series(Y_train)
Y_test= pd.Series(Y_test)

In [17]:
Y_train

0        1593.944216
1        1513.933887
2        1402.612637
3        1278.527266
4        1220.697701
            ...
39403    2392.143374
39404    2349.225766
39405    2365.466215
39406    2229.158338
39407    2086.666645
Length: 39408, dtype: float64

In [18]:
Y_test

0      1936.236898
1      1786.590420
2      1687.829090
3      1600.208464
4      1584.397059
          ...
739    2492.489498
740    2479.958245
741    2485.016884
742    2396.574255
743    2285.252844
Length: 744, dtype: float64

In [19]:
from sklearn.ensemble import RandomForestRegressor
model2 = RandomForestRegressor(n_estimators=100, random_state=0) 
model2.fit(X_train, Y_train)
y_pred2 = model2.predict(X_test)
print('MAPE ', mape(Y_test, y_pred2))

MAPE  14.651866801110636

In [22]:
import eli5
from eli5.sklearn import PermutationImportance
# verilerimizin model üzerindeki etkisini hesaplıyoruz
perm = PermutationImportance(model2, random_state=1).fit(X_test, Y_test)
eli5.show_weights(perm, feature_names = X_test.columns.tolist())